version: "3.4"
services:
  backend_service:
    container_name: backend_service
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 2146422Mahmut
      MYSQL_DATABASE: cointurkiye_database
      MYSQL_USER: cointurkiye_user
      MYSQL_PASSWORD: we5X*vT82
    ports:
      - '3306:3306'
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8880:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
volumes:
  db_data: